export const SHOW_CAPSULE = 'SHOW_CAPSULE'
export const CREATE_USER = 'CREATE_USER'
export const SHOW_USER = 'SHOW_USER'
export const LOGGED_IN = 'LOGGED_IN'
export const LOG_IN = 'LOG_IN'
export const SET_CAPSULES = 'SET_CAPSULES'
export const SET_COLLECTION = 'SET_COLLECTION'